SITJ-3808 added doc for emitterBufferSize
Skatteetaten/aurora pull request #103
Opened 2023-09-19 10:27 UTC by K-Fl

2023-09-19 11:47 UTC, anderius requested changes

2023-09-21 07:25 UTC, K-Fl commented on docs/documentation/aurora-config.md
> +| logging/emitterBufferSize |         | Sets the Emitter_Mem_Buf_Limit for multiline matching *-evalevent_xml or *-ats:eval:xml. Container memory limit is set to `(bufferSize + emitterBufferSize) * 5
La til enheten i docen.

2023-09-22 08:40 UTC, anderius requested changes

2023-09-22 08:40 UTC, anderius commented on .DS_Store
Denne skal ikke med, vel?

2023-09-22 09:04 UTC, anderius approved these changes

2023-09-22 09:06 UTC, merged